version: 1.0.{build}
assembly_info:
  patch: false
platform: Any CPU

environment:
  diadoc_signing_secret:
    secure: prJOj46LFF9HWKRH4PZ8vSS7wgSkkAFIkSCkfqWfAoPNGhUcYqplF4h4PyxEmMjb

install:
  - set JDK_HOME=C:\Program Files\Java\jdk10
  - set JAVA_HOME=C:\Program Files\Java\jdk10
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'http://www-us.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.zip',
          'C:\maven-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
      }
  - set M2_HOME=C:\maven\apache-maven-3.5.4
  - set PATH=%PATH%;C:\maven\apache-maven-3.5.4\bin

  - nuget install secure-file -ExcludeVersion
  - secure-file\tools\secure-file -decrypt jcp-2.0.39014.zip.enc -secret %diadoc_signing_secret%
  - 7z x jcp-2.0.39014.zip
  - cd jcp-2.0.39014
  - mvn install:install-file -Dfile="JCP.jar" -DgroupId="ru.CryptoPro" -DartifactId="JCP" -Dversion="2.0.39014" -Dpackaging="jar"
  - mvn install:install-file -Dfile="asn1rt.jar" -DgroupId="com.objsys.asn1j" -DartifactId="asn1rt" -Dversion="2.0.39014" -Dpackaging="jar"
  - mvn install:install-file -Dfile="ASN1P.jar" -DgroupId="ru.CryptoPro" -DartifactId="ASN1P" -Dversion="2.0.39014" -Dpackaging="jar"
  - mvn install:install-file -Dfile="JCryptoP.jar" -DgroupId="ru.CryptoPro" -DartifactId="JCryptoP" -Dversion="2.0.39014" -Dpackaging="jar"
  - cd ..

build_script:
- ps: .\build.ps1 -Target "AppVeyor" -Verbosity Diagnostic

deploy:
  - provider: GitHub
    release: $(appveyor_repo_tag_name)
    description: 'diadocsdk-java'
    auth_token:
      secure: BSnVMByuW1RN2cKD//7Y2+RRjsmhSfgBd2QK7IpyAadKDh8dIsYe4MF9bvX0SnEz # encrypted token from GitHub
    artifact: /\.jar$/
    draft: false
    prerelease: false
    on:
      branch: master                 # release from master branch only
      appveyor_repo_tag: true        # deploy on tag push only
      appveyor_repo_tag_name: /^versions/
